-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.culture
(

    CONSTRAINT culture_pkey PRIMARY KEY (identifiant_culture)
);

CREATE TABLE IF NOT EXISTS public.date
(

    CONSTRAINT date_pkey PRIMARY KEY (date)
);

CREATE TABLE IF NOT EXISTS public.elements_chimiques
(

    CONSTRAINT elements_chimiques_pkey PRIMARY KEY (code_element)
);

CREATE TABLE IF NOT EXISTS public.engrais
(

    CONSTRAINT engrais_pkey PRIMARY KEY (id_engrais)
);

CREATE TABLE IF NOT EXISTS public.epandre
(

    CONSTRAINT epandre_pkey PRIMARY KEY (id_engrais)
);

CREATE TABLE IF NOT EXISTS public.parcelle
(

    CONSTRAINT parcelle_pkey PRIMARY KEY (no_parcelle)
);

CREATE TABLE IF NOT EXISTS public.posseder
(

    CONSTRAINT posseder_pkey PRIMARY KEY (id_engrais)
);

CREATE TABLE IF NOT EXISTS public.production
(

    CONSTRAINT production_pkey PRIMARY KEY (code_production)
);

CREATE TABLE IF NOT EXISTS public.unite
(

    CONSTRAINT unite_pkey PRIMARY KEY (un)
);

ALTER TABLE IF EXISTS public.culture
    ADD CONSTRAINT code_production FOREIGN KEY (code_production)
    REFERENCES public.production (code_production) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.culture
    ADD CONSTRAINT no_parcelle FOREIGN KEY (no_parcelle)
    REFERENCES public.parcelle (no_parcelle) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.elements_chimiques
    ADD CONSTRAINT un FOREIGN KEY (un)
    REFERENCES public.unite (un) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.engrais
    ADD CONSTRAINT un FOREIGN KEY (un)
    REFERENCES public.unite (un) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.epandre
    ADD CONSTRAINT date FOREIGN KEY (date)
    REFERENCES public.date (date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.epandre
    ADD CONSTRAINT id_engrais FOREIGN KEY (id_engrais)
    REFERENCES public.engrais (id_engrais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS epandre_pkey
    ON public.epandre(id_engrais);


ALTER TABLE IF EXISTS public.epandre
    ADD CONSTRAINT no_parcelle FOREIGN KEY (no_parcelle)
    REFERENCES public.parcelle (no_parcelle) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.posseder
    ADD CONSTRAINT code_element FOREIGN KEY (code_element)
    REFERENCES public.elements_chimiques (code_element) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.posseder
    ADD CONSTRAINT id_engrais FOREIGN KEY (id_engrais)
    REFERENCES public.engrais (id_engrais) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS posseder_pkey
    ON public.posseder(id_engrais);


ALTER TABLE IF EXISTS public.production
    ADD CONSTRAINT un FOREIGN KEY (un)
    REFERENCES public.unite (un) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;